#[allow(dead_code)]
pub fn example_1() -> &'static str {
    "...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#....."
}

pub fn from_file() -> &'static str {
    include_str!("../../../resources/galaxy_map.txt")
}
